button1:
  image: <?php echo sfConfig::get('app_w3s_web_images_dir')?>/image_manager/upload.png
  caption: Import template
  action: W3sTools.openFileUploader(2)
  actionParams:
    class: image_button